name: rossdoell
favicon: null
layout_spectrum: 0.24745
typography_spectrum: 0.46992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363636'
    - '#000000'
    - '#fefefe'
    - '#8e8e8e'
    - '#c2c2c2'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
