name: rossdoell
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8661578104365617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363636'
    - '#000000'
    - '#fefefe'
    - '#8e8e8e'
    - '#c2c2c2'
  brandStrength: 1
  lightness: 0.5189881441183388
  saturation: 0.366495655849576
  rhythmicContrast: 0.8495362286921591
purpose: []
